### ISSUE TITLE
limit: パラメータ無指定の場合に、結果が10件しか出ない

### ISSUE THREAD

**Issue by acokikoy** [tinybeans/jq-plugin-flexibleSearch#5]
limit: パラメータ無指定の場合に、結果が10件しか出ないようです。

データは10件以上あり、ページングはしない想定なので1ページに全件出したいです。
暫定対応として、`limit: 10000` と書いて使っています。

**Comment by tinybeans** [comment]
そうですね、limit を何も指定しない場合は `10` がデフォルトとなります。
したがって、オプションで `limit: 10000` と指定しているのは仕様通りの使い方となります。

**Comment by acokikoy** [comment]
limit の初期値が null とあったので、てっきり全件出力される意味と思っていました。全件出したい場合はどうすればいいですか？ また、デフォルト値の 10 はどこかで定義されているのですか？

**Comment by tinybeans** [comment]
https://github.com/tinybeans/jq-plugin-flexibleSearch/blob/master/flexibleSearch.js#L376

こちらですね。でも仕様としては、あまりよろしくないですね。。。
修正します。

**Comment by tinybeans** [comment]
修正しようと思いましたが、そもそも `limit=10000` の指定で何か問題がありますか？

**Comment by acokikoy** [comment]
実用上の問題はありません！
limitの初期値の解釈で戸惑いましたので、READMEにlimit無指定時の上限について明記いただけるとありがたいです。

**Comment by tinybeans** [comment]
https://github.com/tinybeans/jq-plugin-flexibleSearch/blob/master/README.md#limit

こちらに追記しました！
