### ISSUE TITLE
resultItemTmplの設定例のままだとUncaught ReferenceError: op is not definedというエラーになる

### ISSUE THREAD

**Issue by nakamoto-upost** [tinybeans/jq-plugin-flexibleSearch#6]
README.mdのresultItemTmplの設定例で
```
resultItemTmpl: [
	'<div id="' + op.resultBlockId + '-items">',
    	'<ul>',
    	'{{#items}}',
        	'<li><a href="{{permalink}}">{{&title}}</a></li>',
	    '{{/items}}',
    	'</ul>',
	'</div>'
].join(""),
```
と`op.resultBlockId`をflexibleSearch-config.jsのoptionの中に記述していますが、この書き方だと`op`が定義される前に呼び出されるため`Uncaught ReferenceError: op is not defined`というエラーになってしまいます。

**Comment by tinybeans** [comment]
@nakamoto-upost ご指摘ありがとうございます。
サンプルコードを修正しました。
ee9e042b08e5ebb8cdabb12728eaae89398e6083
